# Generated by Django 3.2.13 on 2022-06-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localgovernmentarea',
            options={'ordering': ['state']},
        ),
    ]
